### ISSUE TITLE
Reverse general/enabled - Why?

### ISSUE THREAD

**Issue by lsv** [magefan/module-community#11]
https://github.com/magefan/module-community/blob/master/Cron/Sections.php#L57

Just why?

**Comment by magefan** [comment]
it's a string "general/enabled"  we don`t want it to be searchable in the code.

**Comment by lsv** [comment]
I know - but why dont you want it to be searchable? - my antivirus is actually giving me a red flag

**Comment by magefan** [comment]
PHP is an open code, so actually anyone can see and change your code. Some unscrupulous developers and store owners can steal modules (and they do) use the modules without the purchase or even rename "Magefan" with their vendor name and sell as its own extension. We have numerous cases of this. Even our free extensions like [Magento 2 Blog](https://github.com/magefan/module-blog) have been stolen, renamed, and sold on other websites. So we adding pain in the ass for them (sorry for the rudeness). strrev is simple and helps us in this fight.

As for antivirus, yes, some of them can show notices, but if you'll check those warnings, you'll see that our Modules are safe to use. Please contact us via email support@magefan.com if you have any other questions or concerns.
