### ISSUE TITLE
Magento 2.3: After a successful installation, am unable to add menu item and Products doesn't on the front end

### ISSUE THREAD

**Issue by moretechgh** [magefan/module-community#14]
After installing SM theme, am unable add both Horizontal and Vertical menu items. 

I can also the products in the Product listing page, which means I can not proceeded to the product listing page. 

How can this issue be solved?

**Comment by magefan** [comment]
@moretechgh , thank you for your report. Unfortunately, we are not vendors of SM theme, we recommend contacting the theme vendor. Or you sure that this issue is related to some of Magefan extensions?
