### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by m-lagiewka** [magefan/module-community#20]
hi,  
just now i was doing an upgrade to 2.4.6  & php8.1 and got the following warnings  
`Warning: Private methods cannot be final as they are never overridden by other classes in /var/www/html/vendor/magefan/module-community/Model/Section.php on line 144`

`Warning: Private methods cannot be final as they are never overridden by other classes in /var/www/html/vendor/magefan/module-community/Model/Section/Info.php on line 83`
  
Nothing urgent, but ugly. Could you possibly do something about it? :)

**Comment by magefan** [comment]
@m-lagiewka , thank you for your report. Think you get this error because of using some old version of magefan/module-community. To fix this issue please update the module to the latest version.

**Comment by m-lagiewka** [comment]
thanks for immediate response, you are right. for some reason wysiwyg advanced module with deps >=2.1.11 pulled exactly this version instead of the newest. could be cache. thanks!
