### ISSUE TITLE
Error after saving a post

### ISSUE THREAD

**Issue by in-session** [magefan/module-community#3]
After creating a post and saving it, we receive the following error message:

Something went wrong while saving this post. Notice: Undefined index: file in /var/www/htdocs/vendor/magefan/module-blog/Controller/Adminhtml/Post/Save.php on line 99
Warning: explode() expects parameter 2 to be string, array given in /var/www/htdocs/vendor/magefan/module-blog/Model/Post.php on line 390

Magento: 2.3.0
magefan/module-community: 2.0.4
magefan/module-blog: 2.8.8

Any idea why?

Greetings Chris

**Comment by magefan** [comment]
Hello @in-session , thank you for your report.
Please try these fixes for [Magento 2 Blog Module](https://magefan.com/magento2-blog-extension):
https://github.com/magefan/module-blog/commit/dcd1ab07eb4aa2416ae32bbba411fe6cf6c205a7
https://github.com/magefan/module-blog/commit/7bb61f7536a8efa6c9dd21907637cbb04db30c96

Let us know if they work well for you.

**Comment by in-session** [comment]
Hi many thanks for your help, after inserting and retesting we get now the follow error:

Something went wrong while saving this post. Notice: Undefined index: position in /var/www/htdocs/vendor/magefan/module-blog/Controller/Adminhtml/Post/Save.php on line 88
Warning: basename() expects parameter 1 to be string, array given in /var/www/htdocs/vendor/magefan/module-blog/Block/Adminhtml/Post/Helper/Form/Gallery.php on line 103

Greetings Chris

**Comment by magefan** [comment]
@in-session ,
1. Fix for the Notice: Undefined index
https://github.com/magefan/module-blog/edit/master/Controller/Adminhtml/Post/Save.php
2. As for Warning: basename() expects parameter 1 
we cannot reproduse this issue, can you please contact us via email support@magefan.com and provide ssh and m2 admin panel credentials so we can check?
