### ISSUE TITLE
Case Sensitivity Problem with "view" Directory

### ISSUE THREAD

**Issue by ElTeteDBit** [magefan/module-community#31]
### Description
I am experiencing an issue with a Magento 2 module where the directory name "view" needs to be capitalized as "View". Failing to do so results in the following error:

`Error: Class "Magefan\Community\View\Helper\SecureHtmlRenderer" not found in /var/www/source/scootfast-magento/generated/code/Magefan/Community/View/Helper/SecureHtmlRenderer/Proxy.php:7`

### Steps to Reproduce
Use the module with the directory named "view".
Attempt to load a page or functionality that utilizes the module.

### Expected Result
The module should function correctly without case sensitivity issues.

**Actual Result**
An error is generated indicating that the class "Magefan\Community\View\Helper\SecureHtmlRenderer" cannot be found.

### Additional Information
Magento 2 version: 2.4.6-p5
Module version: 2.6.2
Renaming the "view" directory to "View" resolves the issue. This appears to be a case sensitivity problem that may affect other environments as well.

### Proposed Solution
Please update the module to ensure the directory is correctly named "View" to avoid case sensitivity issues.

Thank you for your attention to this matter.

**Comment by ElTeteDBit** [comment]
Here are the details about my environment:

- **Magento Version**: Magento 2.4.6-p5
- **PHP Version**: 8.2.20
- **Operating System**: alpine:3.19
- **System Information**: Linux ip-13-0-101-59.eu-west-3.compute.internal 4.14.343-261.564.amzn2.x86_64 #1 SMP Tue May 7 02:23:34 UTC 2024 x86_64 Linux
- **Filesystem Case Sensitivity**: Yes, the OS is case sensitive.

**I apologize for the confusion. The problem is actually in the Google Tag Manager module. If I rename the folder to View everything is working as expected**

<img width="251" alt="image" src="https://github.com/magefan/module-community/assets/172586036/eabe3ea0-07c4-4e4c-873f-12ef550655de">

**Comment by ElTeteDBit** [comment]
> @ElTeteDBit , please don't delete the view folder in the google tag manager extension, it's the wrong solution.
> 
> Could you please try this fix https://github.com/magefan/module-community/pull/32/files ? Don`t forget to run bin/magento setup:di:compile command after you apply changes.
> 
> Let us know if it helps

Yes, it is working right now applying these changes. Thank you 👍 .

Are you going to push this to the master branch?

**Comment by magefan** [comment]
@ElTeteDBit , just released a new version 2.1.28
